import { INumberCountry } from "@isms-core/interfaces";

export const NumberCountries: Array<INumberCountry> = [
  { name: "Vietnam", countryCode: "VN", countryCallingCode: "+84", flag: "🇻🇳" },
  { name: "Andorra", countryCode: "AD", countryCallingCode: "+376", flag: "🇦🇩" },
  { name: "United Arab Emirates", countryCode: "AE", countryCallingCode: "+971", flag: "🇦🇪" },
  { name: "Afghanistan", countryCode: "AF", countryCallingCode: "+93", flag: "🇦🇫" },
  { name: "Antigua & Barbuda", countryCode: "AG", countryCallingCode: "+1268", flag: "🇦🇬" },
  { name: "Anguilla", countryCode: "AI", countryCallingCode: "+1264", flag: "🇦🇮" },
  { name: "Albania", countryCode: "AL", countryCallingCode: "+355", flag: "🇦🇱" },
  { name: "Armenia", countryCode: "AM", countryCallingCode: "+374", flag: "🇦🇲" },
  { name: "Angola", countryCode: "AO", countryCallingCode: "+244", flag: "🇦🇴" },
  { name: "Antarctica", countryCode: "AQ", countryCallingCode: "+672", flag: "🇦🇶" },
  { name: "Argentina", countryCode: "AR", countryCallingCode: "+54", flag: "🇦🇷" },
  { name: "American Samoa", countryCode: "AS", countryCallingCode: "+1684", flag: "🇦🇸" },
  { name: "Austria", countryCode: "AT", countryCallingCode: "+43", flag: "🇦🇹" },
  { name: "Australia", countryCode: "AU", countryCallingCode: "+61", flag: "🇦🇺" },
  { name: "Aruba", countryCode: "AW", countryCallingCode: "+297", flag: "🇦🇼" },
  { name: "Åland Islands", countryCode: "AX", countryCallingCode: "+358", flag: "🇦🇽" },
  { name: "Azerbaijan", countryCode: "AZ", countryCallingCode: "+994", flag: "🇦🇿" },
  { name: "Bosnia & Herzegovina", countryCode: "BA", countryCallingCode: "+387", flag: "🇧🇦" },
  { name: "Barbados", countryCode: "BB", countryCallingCode: "+1246", flag: "🇧🇧" },
  { name: "Bangladesh", countryCode: "BD", countryCallingCode: "+880", flag: "🇧🇩" },
  { name: "Belgium", countryCode: "BE", countryCallingCode: "+32", flag: "🇧🇪" },
  { name: "Burkina Faso", countryCode: "BF", countryCallingCode: "+226", flag: "🇧🇫" },
  { name: "Bulgaria", countryCode: "BG", countryCallingCode: "+359", flag: "🇧🇬" },
  { name: "Bahrain", countryCode: "BH", countryCallingCode: "+973", flag: "🇧🇭" },
  { name: "Burundi", countryCode: "BI", countryCallingCode: "+257", flag: "🇧🇮" },
  { name: "Benin", countryCode: "BJ", countryCallingCode: "+229", flag: "🇧🇯" },
  { name: "St. Barthélemy", countryCode: "BL", countryCallingCode: "+590", flag: "🇧🇱" },
  { name: "Bermuda", countryCode: "BM", countryCallingCode: "+1441", flag: "🇧🇲" },
  { name: "Brunei", countryCode: "BN", countryCallingCode: "+673", flag: "🇧🇳" },
  { name: "Bolivia", countryCode: "BO", countryCallingCode: "+591", flag: "🇧🇴" },
  { name: "Brazil", countryCode: "BR", countryCallingCode: "+55", flag: "🇧🇷" },
  { name: "Bahamas", countryCode: "BS", countryCallingCode: "+1242", flag: "🇧🇸" },
  { name: "Bhutan", countryCode: "BT", countryCallingCode: "+975", flag: "🇧🇹" },
  { name: "Botswana", countryCode: "BW", countryCallingCode: "+267", flag: "🇧🇼" },
  { name: "Belarus", countryCode: "BY", countryCallingCode: "+375", flag: "🇧🇾" },
  { name: "Belize", countryCode: "BZ", countryCallingCode: "+501", flag: "🇧🇿" },
  { name: "Canada", countryCode: "CA", countryCallingCode: "+1", flag: "🇨🇦" },
  { name: "Cocos (Keeling) Islands", countryCode: "CC", countryCallingCode: "+61", flag: "🇨🇨" },
  { name: "Congo - Kinshasa", countryCode: "CD", countryCallingCode: "+243", flag: "🇨🇩" },
  { name: "Central African Republic", countryCode: "CF", countryCallingCode: "+236", flag: "🇨🇫" },
  { name: "Congo - Brazzaville", countryCode: "CG", countryCallingCode: "+242", flag: "🇨🇬" },
  { name: "Switzerland", countryCode: "CH", countryCallingCode: "+41", flag: "🇨🇭" },
  { name: "Côte d’Ivoire", countryCode: "CI", countryCallingCode: "+225", flag: "🇨🇮" },
  { name: "Cook Islands", countryCode: "CK", countryCallingCode: "+682", flag: "🇨🇰" },
  { name: "Chile", countryCode: "CL", countryCallingCode: "+56", flag: "🇨🇱" },
  { name: "Cameroon", countryCode: "CM", countryCallingCode: "+237", flag: "🇨🇲" },
  { name: "China", countryCode: "CN", countryCallingCode: "+86", flag: "🇨🇳" },
  { name: "Colombia", countryCode: "CO", countryCallingCode: "+57", flag: "🇨🇴" },
  { name: "Costa Rica", countryCode: "CR", countryCallingCode: "+506", flag: "🇨🇷" },
  { name: "Cuba", countryCode: "CU", countryCallingCode: "+53", flag: "🇨🇺" },
  { name: "Cape Verde", countryCode: "CV", countryCallingCode: "+238", flag: "🇨🇻" },
  { name: "Christmas Island", countryCode: "CX", countryCallingCode: "+61", flag: "🇨🇽" },
  { name: "Cyprus", countryCode: "CY", countryCallingCode: "+357", flag: "🇨🇾" },
  { name: "Czechia", countryCode: "CZ", countryCallingCode: "+420", flag: "🇨🇿" },
  { name: "Germany", countryCode: "DE", countryCallingCode: "+49", flag: "🇩🇪" },
  { name: "Djibouti", countryCode: "DJ", countryCallingCode: "+253", flag: "🇩🇯" },
  { name: "Denmark", countryCode: "DK", countryCallingCode: "+45", flag: "🇩🇰" },
  { name: "Dominica", countryCode: "DM", countryCallingCode: "+1767", flag: "🇩🇲" },
  { name: "Dominican Republic", countryCode: "DO", countryCallingCode: "+1849", flag: "🇩🇴" },
  { name: "Algeria", countryCode: "DZ", countryCallingCode: "+213", flag: "🇩🇿" },
  { name: "Ecuador", countryCode: "EC", countryCallingCode: "+593", flag: "🇪🇨" },
  { name: "Estonia", countryCode: "EE", countryCallingCode: "+372", flag: "🇪🇪" },
  { name: "Egypt", countryCode: "EG", countryCallingCode: "+20", flag: "🇪🇬" },
  { name: "Eritrea", countryCode: "ER", countryCallingCode: "+291", flag: "🇪🇷" },
  { name: "Spain", countryCode: "ES", countryCallingCode: "+34", flag: "🇪🇸" },
  { name: "Ethiopia", countryCode: "ET", countryCallingCode: "+251", flag: "🇪🇹" },
  { name: "Finland", countryCode: "FI", countryCallingCode: "+358", flag: "🇫🇮" },
  { name: "Fiji", countryCode: "FJ", countryCallingCode: "+679", flag: "🇫🇯" },
  { name: "Falkland Islands", countryCode: "FK", countryCallingCode: "+500", flag: "🇫🇰" },
  { name: "Micronesia", countryCode: "FM", countryCallingCode: "+691", flag: "🇫🇲" },
  { name: "Faroe Islands", countryCode: "FO", countryCallingCode: "+298", flag: "🇫🇴" },
  { name: "France", countryCode: "FR", countryCallingCode: "+33", flag: "🇫🇷" },
  { name: "Gabon", countryCode: "GA", countryCallingCode: "+241", flag: "🇬🇦" },
  { name: "United Kingdom", countryCode: "GB", countryCallingCode: "+44", flag: "🇬🇧" },
  { name: "Grenada", countryCode: "GD", countryCallingCode: "+1473", flag: "🇬🇩" },
  { name: "Georgia", countryCode: "GE", countryCallingCode: "+995", flag: "🇬🇪" },
  { name: "French Guiana", countryCode: "GF", countryCallingCode: "+594", flag: "🇬🇫" },
  { name: "Guernsey", countryCode: "GG", countryCallingCode: "+44", flag: "🇬🇬" },
  { name: "Ghana", countryCode: "GH", countryCallingCode: "+233", flag: "🇬🇭" },
  { name: "Gibraltar", countryCode: "GI", countryCallingCode: "+350", flag: "🇬🇮" },
  { name: "Greenland", countryCode: "GL", countryCallingCode: "+299", flag: "🇬🇱" },
  { name: "Gambia", countryCode: "GM", countryCallingCode: "+220", flag: "🇬🇲" },
  { name: "Guinea", countryCode: "GN", countryCallingCode: "+224", flag: "🇬🇳" },
  { name: "Guadeloupe", countryCode: "GP", countryCallingCode: "+590", flag: "🇬🇵" },
  { name: "Equatorial Guinea", countryCode: "GQ", countryCallingCode: "+240", flag: "🇬🇶" },
  { name: "Greece", countryCode: "GR", countryCallingCode: "+30", flag: "🇬🇷" },
  { name: "South Georgia & South Sandwich Islands", countryCode: "GS", countryCallingCode: "+500", flag: "🇬🇸" },
  { name: "Guatemala", countryCode: "GT", countryCallingCode: "+502", flag: "🇬🇹" },
  { name: "Guam", countryCode: "GU", countryCallingCode: "+1671", flag: "🇬🇺" },
  { name: "Guinea-Bissau", countryCode: "GW", countryCallingCode: "+245", flag: "🇬🇼" },
  { name: "Guyana", countryCode: "GY", countryCallingCode: "+595", flag: "🇬🇾" },
  { name: "Hong Kong SAR China", countryCode: "HK", countryCallingCode: "+852", flag: "🇭🇰" },
  { name: "Honduras", countryCode: "HN", countryCallingCode: "+504", flag: "🇭🇳" },
  { name: "Croatia", countryCode: "HR", countryCallingCode: "+385", flag: "🇭🇷" },
  { name: "Haiti", countryCode: "HT", countryCallingCode: "+509", flag: "🇭🇹" },
  { name: "Hungary", countryCode: "HU", countryCallingCode: "+36", flag: "🇭🇺" },
  { name: "Indonesia", countryCode: "ID", countryCallingCode: "+62", flag: "🇮🇩" },
  { name: "Ireland", countryCode: "IE", countryCallingCode: "+353", flag: "🇮🇪" },
  { name: "Israel", countryCode: "IL", countryCallingCode: "+972", flag: "🇮🇱" },
  { name: "Isle of Man", countryCode: "IM", countryCallingCode: "+44", flag: "🇮🇲" },
  { name: "India", countryCode: "IN", countryCallingCode: "+91", flag: "🇮🇳" },
  { name: "British Indian Ocean Territory", countryCode: "IO", countryCallingCode: "+246", flag: "🇮🇴" },
  { name: "Iraq", countryCode: "IQ", countryCallingCode: "+964", flag: "🇮🇶" },
  { name: "Iran", countryCode: "IR", countryCallingCode: "+98", flag: "🇮🇷" },
  { name: "Iceland", countryCode: "IS", countryCallingCode: "+354", flag: "🇮🇸" },
  { name: "Italy", countryCode: "IT", countryCallingCode: "+39", flag: "🇮🇹" },
  { name: "Jersey", countryCode: "JE", countryCallingCode: "+44", flag: "🇯🇪" },
  { name: "Jamaica", countryCode: "JM", countryCallingCode: "+1876", flag: "🇯🇲" },
  { name: "Jordan", countryCode: "JO", countryCallingCode: "+962", flag: "🇯🇴" },
  { name: "Japan", countryCode: "JP", countryCallingCode: "+81", flag: "🇯🇵" },
  { name: "Kenya", countryCode: "KE", countryCallingCode: "+254", flag: "🇰🇪" },
  { name: "Kyrgyzstan", countryCode: "KG", countryCallingCode: "+996", flag: "🇰🇬" },
  { name: "Cambodia", countryCode: "KH", countryCallingCode: "+855", flag: "🇰🇭" },
  { name: "Kiribati", countryCode: "KI", countryCallingCode: "+686", flag: "🇰🇮" },
  { name: "Comoros", countryCode: "KM", countryCallingCode: "+269", flag: "🇰🇲" },
  { name: "St. Kitts & Nevis", countryCode: "KN", countryCallingCode: "+1869", flag: "🇰🇳" },
  { name: "North Korea", countryCode: "KP", countryCallingCode: "+850", flag: "🇰🇵" },
  { name: "South Korea", countryCode: "KR", countryCallingCode: "+82", flag: "🇰🇷" },
  { name: "Kuwait", countryCode: "KW", countryCallingCode: "+965", flag: "🇰🇼" },
  { name: "Cayman Islands", countryCode: "KY", countryCallingCode: "+ 345", flag: "🇰🇾" },
  { name: "Kazakhstan", countryCode: "KZ", countryCallingCode: "+77", flag: "🇰🇿" },
  { name: "Laos", countryCode: "LA", countryCallingCode: "+856", flag: "🇱🇦" },
  { name: "Lebanon", countryCode: "LB", countryCallingCode: "+961", flag: "🇱🇧" },
  { name: "St. Lucia", countryCode: "LC", countryCallingCode: "+1758", flag: "🇱🇨" },
  { name: "Liechtenstein", countryCode: "LI", countryCallingCode: "+423", flag: "🇱🇮" },
  { name: "Sri Lanka", countryCode: "LK", countryCallingCode: "+94", flag: "🇱🇰" },
  { name: "Liberia", countryCode: "LR", countryCallingCode: "+231", flag: "🇱🇷" },
  { name: "Lesotho", countryCode: "LS", countryCallingCode: "+266", flag: "🇱🇸" },
  { name: "Lithuania", countryCode: "LT", countryCallingCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", countryCode: "LU", countryCallingCode: "+352", flag: "🇱🇺" },
  { name: "Latvia", countryCode: "LV", countryCallingCode: "+371", flag: "🇱🇻" },
  { name: "Libya", countryCode: "LY", countryCallingCode: "+218", flag: "🇱🇾" },
  { name: "Morocco", countryCode: "MA", countryCallingCode: "+212", flag: "🇲🇦" },
  { name: "Monaco", countryCode: "MC", countryCallingCode: "+377", flag: "🇲🇨" },
  { name: "Moldova", countryCode: "MD", countryCallingCode: "+373", flag: "🇲🇩" },
  { name: "Montenegro", countryCode: "ME", countryCallingCode: "+382", flag: "🇲🇪" },
  { name: "St. Martin", countryCode: "MF", countryCallingCode: "+590", flag: "🇲🇫" },
  { name: "Madagascar", countryCode: "MG", countryCallingCode: "+261", flag: "🇲🇬" },
  { name: "Marshall Islands", countryCode: "MH", countryCallingCode: "+692", flag: "🇲🇭" },
  { name: "North Macedonia", countryCode: "MK", countryCallingCode: "+389", flag: "🇲🇰" },
  { name: "Mali", countryCode: "ML", countryCallingCode: "+223", flag: "🇲🇱" },
  { name: "Myanmar (Burma)", countryCode: "MM", countryCallingCode: "+95", flag: "🇲🇲" },
  { name: "Mongolia", countryCode: "MN", countryCallingCode: "+976", flag: "🇲🇳" },
  { name: "Macao SAR China", countryCode: "MO", countryCallingCode: "+853", flag: "🇲🇴" },
  { name: "Northern Mariana Islands", countryCode: "MP", countryCallingCode: "+1670", flag: "🇲🇵" },
  { name: "Martinique", countryCode: "MQ", countryCallingCode: "+596", flag: "🇲🇶" },
  { name: "Mauritania", countryCode: "MR", countryCallingCode: "+222", flag: "🇲🇷" },
  { name: "Montserrat", countryCode: "MS", countryCallingCode: "+1664", flag: "🇲🇸" },
  { name: "Malta", countryCode: "MT", countryCallingCode: "+356", flag: "🇲🇹" },
  { name: "Mauritius", countryCode: "MU", countryCallingCode: "+230", flag: "🇲🇺" },
  { name: "Maldives", countryCode: "MV", countryCallingCode: "+960", flag: "🇲🇻" },
  { name: "Malawi", countryCode: "MW", countryCallingCode: "+265", flag: "🇲🇼" },
  { name: "Mexico", countryCode: "MX", countryCallingCode: "+52", flag: "🇲🇽" },
  { name: "Malaysia", countryCode: "MY", countryCallingCode: "+60", flag: "🇲🇾" },
  { name: "Mozambique", countryCode: "MZ", countryCallingCode: "+258", flag: "🇲🇿" },
  { name: "Namibia", countryCode: "NA", countryCallingCode: "+264", flag: "🇳🇦" },
  { name: "New Caledonia", countryCode: "NC", countryCallingCode: "+687", flag: "🇳🇨" },
  { name: "Niger", countryCode: "NE", countryCallingCode: "+227", flag: "🇳🇪" },
  { name: "Norfolk Island", countryCode: "NF", countryCallingCode: "+672", flag: "🇳🇫" },
  { name: "Nigeria", countryCode: "NG", countryCallingCode: "+234", flag: "🇳🇬" },
  { name: "Nicaragua", countryCode: "NI", countryCallingCode: "+505", flag: "🇳🇮" },
  { name: "Netherlands", countryCode: "NL", countryCallingCode: "+31", flag: "🇳🇱" },
  { name: "Norway", countryCode: "NO", countryCallingCode: "+47", flag: "🇳🇴" },
  { name: "Nepal", countryCode: "NP", countryCallingCode: "+977", flag: "🇳🇵" },
  { name: "Nauru", countryCode: "NR", countryCallingCode: "+674", flag: "🇳🇷" },
  { name: "Niue", countryCode: "NU", countryCallingCode: "+683", flag: "🇳🇺" },
  { name: "New Zealand", countryCode: "NZ", countryCallingCode: "+64", flag: "🇳🇿" },
  { name: "Oman", countryCode: "OM", countryCallingCode: "+968", flag: "🇴🇲" },
  { name: "Panama", countryCode: "PA", countryCallingCode: "+507", flag: "🇵🇦" },
  { name: "Peru", countryCode: "PE", countryCallingCode: "+51", flag: "🇵🇪" },
  { name: "French Polynesia", countryCode: "PF", countryCallingCode: "+689", flag: "🇵🇫" },
  { name: "Papua New Guinea", countryCode: "PG", countryCallingCode: "+675", flag: "🇵🇬" },
  { name: "Philippines", countryCode: "PH", countryCallingCode: "+63", flag: "🇵🇭" },
  { name: "Pakistan", countryCode: "PK", countryCallingCode: "+92", flag: "🇵🇰" },
  { name: "Poland", countryCode: "PL", countryCallingCode: "+48", flag: "🇵🇱" },
  { name: "St. Pierre & Miquelon", countryCode: "PM", countryCallingCode: "+508", flag: "🇵🇲" },
  { name: "Pitcairn Islands", countryCode: "PN", countryCallingCode: "+872", flag: "🇵🇳" },
  { name: "Puerto Rico", countryCode: "PR", countryCallingCode: "+1939", flag: "🇵🇷" },
  { name: "Palestinian Territories", countryCode: "PS", countryCallingCode: "+970", flag: "🇵🇸" },
  { name: "Portugal", countryCode: "PT", countryCallingCode: "+351", flag: "🇵🇹" },
  { name: "Palau", countryCode: "PW", countryCallingCode: "+680", flag: "🇵🇼" },
  { name: "Paraguay", countryCode: "PY", countryCallingCode: "+595", flag: "🇵🇾" },
  { name: "Qatar", countryCode: "QA", countryCallingCode: "+974", flag: "🇶🇦" },
  { name: "Réunion", countryCode: "RE", countryCallingCode: "+262", flag: "🇷🇪" },
  { name: "Romania", countryCode: "RO", countryCallingCode: "+40", flag: "🇷🇴" },
  { name: "Serbia", countryCode: "RS", countryCallingCode: "+381", flag: "🇷🇸" },
  { name: "Russia", countryCode: "RU", countryCallingCode: "+7", flag: "🇷🇺" },
  { name: "Rwanda", countryCode: "RW", countryCallingCode: "+250", flag: "🇷🇼" },
  { name: "Saudi Arabia", countryCode: "SA", countryCallingCode: "+966", flag: "🇸🇦" },
  { name: "Solomon Islands", countryCode: "SB", countryCallingCode: "+677", flag: "🇸🇧" },
  { name: "Seychelles", countryCode: "SC", countryCallingCode: "+248", flag: "🇸🇨" },
  { name: "Sudan", countryCode: "SD", countryCallingCode: "+249", flag: "🇸🇩" },
  { name: "Sweden", countryCode: "SE", countryCallingCode: "+46", flag: "🇸🇪" },
  { name: "Singapore", countryCode: "SG", countryCallingCode: "+65", flag: "🇸🇬" },
  { name: "St. Helena", countryCode: "SH", countryCallingCode: "+290", flag: "🇸🇭" },
  { name: "Slovenia", countryCode: "SI", countryCallingCode: "+386", flag: "🇸🇮" },
  { name: "Svalbard & Jan Mayen", countryCode: "SJ", countryCallingCode: "+47", flag: "🇸🇯" },
  { name: "Slovakia", countryCode: "SK", countryCallingCode: "+421", flag: "🇸🇰" },
  { name: "Sierra Leone", countryCode: "SL", countryCallingCode: "+232", flag: "🇸🇱" },
  { name: "San Marino", countryCode: "SM", countryCallingCode: "+378", flag: "🇸🇲" },
  { name: "Senegal", countryCode: "SN", countryCallingCode: "+221", flag: "🇸🇳" },
  { name: "Somalia", countryCode: "SO", countryCallingCode: "+252", flag: "🇸🇴" },
  { name: "Suriname", countryCode: "SR", countryCallingCode: "+597", flag: "🇸🇷" },
  { name: "South Sudan", countryCode: "SS", countryCallingCode: "+211", flag: "🇸🇸" },
  { name: "São Tomé & Príncipe", countryCode: "ST", countryCallingCode: "+239", flag: "🇸🇹" },
  { name: "El Salvador", countryCode: "SV", countryCallingCode: "+503", flag: "🇸🇻" },
  { name: "Syria", countryCode: "SY", countryCallingCode: "+963", flag: "🇸🇾" },
  { name: "Eswatini", countryCode: "SZ", countryCallingCode: "+268", flag: "🇸🇿" },
  { name: "Turks & Caicos Islands", countryCode: "TC", countryCallingCode: "+1649", flag: "🇹🇨" },
  { name: "Chad", countryCode: "TD", countryCallingCode: "+235", flag: "🇹🇩" },
  { name: "Togo", countryCode: "TG", countryCallingCode: "+228", flag: "🇹🇬" },
  { name: "Thailand", countryCode: "TH", countryCallingCode: "+66", flag: "🇹🇭" },
  { name: "Tajikistan", countryCode: "TJ", countryCallingCode: "+992", flag: "🇹🇯" },
  { name: "Tokelau", countryCode: "TK", countryCallingCode: "+690", flag: "🇹🇰" },
  { name: "Timor-Leste", countryCode: "TL", countryCallingCode: "+670", flag: "🇹🇱" },
  { name: "Turkmenistan", countryCode: "TM", countryCallingCode: "+993", flag: "🇹🇲" },
  { name: "Tunisia", countryCode: "TN", countryCallingCode: "+216", flag: "🇹🇳" },
  { name: "Tonga", countryCode: "TO", countryCallingCode: "+676", flag: "🇹🇴" },
  { name: "Turkey", countryCode: "TR", countryCallingCode: "+90", flag: "🇹🇷" },
  { name: "Trinidad & Tobago", countryCode: "TT", countryCallingCode: "+1868", flag: "🇹🇹" },
  { name: "Tuvalu", countryCode: "TV", countryCallingCode: "+688", flag: "🇹🇻" },
  { name: "Taiwan", countryCode: "TW", countryCallingCode: "+886", flag: "🇹🇼" },
  { name: "Tanzania", countryCode: "TZ", countryCallingCode: "+255", flag: "🇹🇿" },
  { name: "Ukraine", countryCode: "UA", countryCallingCode: "+380", flag: "🇺🇦" },
  { name: "Uganda", countryCode: "UG", countryCallingCode: "+256", flag: "🇺🇬" },
  { name: "United States", countryCode: "US", countryCallingCode: "+1", flag: "🇺🇸" },
  { name: "Uruguay", countryCode: "UY", countryCallingCode: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", countryCode: "UZ", countryCallingCode: "+998", flag: "🇺🇿" },
  { name: "Vatican City", countryCode: "VA", countryCallingCode: "+379", flag: "🇻🇦" },
  { name: "St. Vincent & Grenadines", countryCode: "VC", countryCallingCode: "+1784", flag: "🇻🇨" },
  { name: "Venezuela", countryCode: "VE", countryCallingCode: "+58", flag: "🇻🇪" },
  { name: "British Virgin Islands", countryCode: "VG", countryCallingCode: "+1284", flag: "🇻🇬" },
  { name: "U.S. Virgin Islands", countryCode: "VI", countryCallingCode: "+1340", flag: "🇻🇮" },
  // { name: "Vietnam", countryCode: "VN", countryCallingCode: "+84", flag: "🇻🇳" },
  { name: "Vanuatu", countryCode: "VU", countryCallingCode: "+678", flag: "🇻🇺" },
  { name: "Wallis & Futuna", countryCode: "WF", countryCallingCode: "+681", flag: "🇼🇫" },
  { name: "Samoa", countryCode: "WS", countryCallingCode: "+685", flag: "🇼🇸" },
  { name: "Yemen", countryCode: "YE", countryCallingCode: "+967", flag: "🇾🇪" },
  { name: "Mayotte", countryCode: "YT", countryCallingCode: "+262", flag: "🇾🇹" },
  { name: "South Africa", countryCode: "ZA", countryCallingCode: "+27", flag: "🇿🇦" },
  { name: "Zambia", countryCode: "ZM", countryCallingCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", countryCode: "ZW", countryCallingCode: "+263", flag: "🇿🇼" },
];
