export const Timezones = [
  {
    offset: "+07:00",
    label: "Indochina Time - Ho Chi Minh City",
    timezone: "Asia/Ho_Chi_Minh",
  },
  { offset: "-11:00", label: "Niue Time", timezone: "Pacific/Niue" },
  {
    offset: "-11:00",
    label: "Samoa Standard Time",
    timezone: "Pacific/Pago_Pago",
  },
  {
    offset: "-10:00",
    label: "Cook Islands Standard Time",
    timezone: "Pacific/Rarotonga",
  },
  {
    offset: "-10:00",
    label: "Hawaii-Aleutian Standard Time",
    timezone: "Pacific/Honolulu",
  },
  { offset: "-10:00", label: "Tahiti Time", timezone: "Pacific/Tahiti" },
  {
    offset: "-09:30",
    label: "Marquesas Time",
    timezone: "Pacific/Marquesas",
  },
  { offset: "-09:00", label: "Gambier Time", timezone: "Pacific/Gambier" },
  {
    offset: "-09:00",
    label: "Hawaii-Aleutian Time (Adak)",
    timezone: "America/Adak",
  },
  {
    offset: "-08:00",
    label: "Alaska Time - Anchorage",
    timezone: "America/Anchorage",
  },
  {
    offset: "-08:00",
    label: "Alaska Time - Juneau",
    timezone: "America/Juneau",
  },
  {
    offset: "-08:00",
    label: "Alaska Time - Metlakatla",
    timezone: "America/Metlakatla",
  },
  {
    offset: "-08:00",
    label: "Alaska Time - Nome",
    timezone: "America/Nome",
  },
  {
    offset: "-08:00",
    label: "Alaska Time - Sitka",
    timezone: "America/Sitka",
  },
  {
    offset: "-08:00",
    label: "Alaska Time - Yakutat",
    timezone: "America/Yakutat",
  },
  {
    offset: "-08:00",
    label: "Pitcairn Time",
    timezone: "Pacific/Pitcairn",
  },
  {
    offset: "-07:00",
    label: "Mexican Pacific Standard Time - Hermosillo",
    timezone: "America/Hermosillo",
  },
  {
    offset: "-07:00",
    label: "Mexican Pacific Standard Time - Mazatlan",
    timezone: "America/Mazatlan",
  },
  {
    offset: "-07:00",
    label: "Mountain Standard Time - Dawson Creek",
    timezone: "America/Dawson_Creek",
  },
  {
    offset: "-07:00",
    label: "Mountain Standard Time - Fort Nelson",
    timezone: "America/Fort_Nelson",
  },
  {
    offset: "-07:00",
    label: "Mountain Standard Time - Phoenix",
    timezone: "America/Phoenix",
  },
  {
    offset: "-07:00",
    label: "Pacific Time - Los Angeles",
    timezone: "America/Los_Angeles",
  },
  {
    offset: "-07:00",
    label: "Pacific Time - Tijuana",
    timezone: "America/Tijuana",
  },
  {
    offset: "-07:00",
    label: "Pacific Time - Vancouver",
    timezone: "America/Vancouver",
  },
  {
    offset: "-07:00",
    label: "Yukon Time - Dawson",
    timezone: "America/Dawson",
  },
  {
    offset: "-07:00",
    label: "Yukon Time - Whitehorse",
    timezone: "America/Whitehorse",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Bahía de Banderas",
    timezone: "America/Bahia_Banderas",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Belize",
    timezone: "America/Belize",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Chihuahua",
    timezone: "America/Chihuahua",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Costa Rica",
    timezone: "America/Costa_Rica",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - El Salvador",
    timezone: "America/El_Salvador",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Guatemala",
    timezone: "America/Guatemala",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Managua",
    timezone: "America/Managua",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Mérida",
    timezone: "America/Merida",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Mexico City",
    timezone: "America/Mexico_City",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Monterrey",
    timezone: "America/Monterrey",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Regina",
    timezone: "America/Regina",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Swift Current",
    timezone: "America/Swift_Current",
  },
  {
    offset: "-06:00",
    label: "Central Standard Time - Tegucigalpa",
    timezone: "America/Tegucigalpa",
  },
  {
    offset: "-06:00",
    label: "Easter Island Time",
    timezone: "Pacific/Easter",
  },
  {
    offset: "-06:00",
    label: "Galapagos Time",
    timezone: "Pacific/Galapagos",
  },
  {
    offset: "-06:00",
    label: "Mountain Time - Boise",
    timezone: "America/Boise",
  },
  {
    offset: "-06:00",
    label: "Mountain Time - Cambridge Bay",
    timezone: "America/Cambridge_Bay",
  },
  {
    offset: "-06:00",
    label: "Mountain Time - Ciudad Juárez",
    timezone: "America/Ciudad_Juarez",
  },
  {
    offset: "-06:00",
    label: "Mountain Time - Denver",
    timezone: "America/Denver",
  },
  {
    offset: "-06:00",
    label: "Mountain Time - Edmonton",
    timezone: "America/Edmonton",
  },
  {
    offset: "-06:00",
    label: "Mountain Time - Inuvik",
    timezone: "America/Inuvik",
  },
  {
    offset: "-06:00",
    label: "Mountain Time - Yellowknife",
    timezone: "America/Yellowknife",
  },
  {
    offset: "-05:00",
    label: "Acre Standard Time - Eirunepe",
    timezone: "America/Eirunepe",
  },
  {
    offset: "-05:00",
    label: "Acre Standard Time - Rio Branco",
    timezone: "America/Rio_Branco",
  },
  {
    offset: "-05:00",
    label: "Central Time - Beulah, North Dakota",
    timezone: "America/North_Dakota/Beulah",
  },
  {
    offset: "-05:00",
    label: "Central Time - Center, North Dakota",
    timezone: "America/North_Dakota/Center",
  },
  {
    offset: "-05:00",
    label: "Central Time - Chicago",
    timezone: "America/Chicago",
  },
  {
    offset: "-05:00",
    label: "Central Time - Knox, Indiana",
    timezone: "America/Indiana/Knox",
  },
  {
    offset: "-05:00",
    label: "Central Time - Matamoros",
    timezone: "America/Matamoros",
  },
  {
    offset: "-05:00",
    label: "Central Time - Menominee",
    timezone: "America/Menominee",
  },
  {
    offset: "-05:00",
    label: "Central Time - New Salem, North Dakota",
    timezone: "America/North_Dakota/New_Salem",
  },
  {
    offset: "-05:00",
    label: "Central Time - Ojinaga",
    timezone: "America/Ojinaga",
  },
  {
    offset: "-05:00",
    label: "Central Time - Rainy River",
    timezone: "America/Rainy_River",
  },
  {
    offset: "-05:00",
    label: "Central Time - Rankin Inlet",
    timezone: "America/Rankin_Inlet",
  },
  {
    offset: "-05:00",
    label: "Central Time - Resolute",
    timezone: "America/Resolute",
  },
  {
    offset: "-05:00",
    label: "Central Time - Tell City, Indiana",
    timezone: "America/Indiana/Tell_City",
  },
  {
    offset: "-05:00",
    label: "Central Time - Winnipeg",
    timezone: "America/Winnipeg",
  },
  {
    offset: "-05:00",
    label: "Colombia Standard Time",
    timezone: "America/Bogota",
  },
  {
    offset: "-05:00",
    label: "Eastern Standard Time - Cancún",
    timezone: "America/Cancun",
  },
  {
    offset: "-05:00",
    label: "Eastern Standard Time - Jamaica",
    timezone: "America/Jamaica",
  },
  {
    offset: "-05:00",
    label: "Eastern Standard Time - Panama",
    timezone: "America/Panama",
  },
  {
    offset: "-05:00",
    label: "Ecuador Time",
    timezone: "America/Guayaquil",
  },
  {
    offset: "-05:00",
    label: "Peru Standard Time",
    timezone: "America/Lima",
  },
  {
    offset: "-04:00",
    label: "Amazon Standard Time - Boa Vista",
    timezone: "America/Boa_Vista",
  },
  {
    offset: "-04:00",
    label: "Amazon Standard Time - Campo Grande",
    timezone: "America/Campo_Grande",
  },
  {
    offset: "-04:00",
    label: "Amazon Standard Time - Cuiaba",
    timezone: "America/Cuiaba",
  },
  {
    offset: "-04:00",
    label: "Amazon Standard Time - Manaus",
    timezone: "America/Manaus",
  },
  {
    offset: "-04:00",
    label: "Amazon Standard Time - Porto Velho",
    timezone: "America/Porto_Velho",
  },
  {
    offset: "-04:00",
    label: "Atlantic Standard Time - Barbados",
    timezone: "America/Barbados",
  },
  {
    offset: "-04:00",
    label: "Atlantic Standard Time - Martinique",
    timezone: "America/Martinique",
  },
  {
    offset: "-04:00",
    label: "Atlantic Standard Time - Puerto Rico",
    timezone: "America/Puerto_Rico",
  },
  {
    offset: "-04:00",
    label: "Atlantic Standard Time - Santo Domingo",
    timezone: "America/Santo_Domingo",
  },
  { offset: "-04:00", label: "Bolivia Time", timezone: "America/La_Paz" },
  { offset: "-04:00", label: "Chile Time", timezone: "America/Santiago" },
  { offset: "-04:00", label: "Cuba Time", timezone: "America/Havana" },
  {
    offset: "-04:00",
    label: "Eastern Time - Detroit",
    timezone: "America/Detroit",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Grand Turk",
    timezone: "America/Grand_Turk",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Indianapolis",
    timezone: "America/Indiana/Indianapolis",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Iqaluit",
    timezone: "America/Iqaluit",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Louisville",
    timezone: "America/Kentucky/Louisville",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Marengo, Indiana",
    timezone: "America/Indiana/Marengo",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Monticello, Kentucky",
    timezone: "America/Kentucky/Monticello",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - New York",
    timezone: "America/New_York",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Nipigon",
    timezone: "America/Nipigon",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Pangnirtung",
    timezone: "America/Pangnirtung",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Petersburg, Indiana",
    timezone: "America/Indiana/Petersburg",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Port-au-Prince",
    timezone: "America/Port-au-Prince",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Thunder Bay",
    timezone: "America/Thunder_Bay",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Toronto",
    timezone: "America/Toronto",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Vevay, Indiana",
    timezone: "America/Indiana/Vevay",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Vincennes, Indiana",
    timezone: "America/Indiana/Vincennes",
  },
  {
    offset: "-04:00",
    label: "Eastern Time - Winamac, Indiana",
    timezone: "America/Indiana/Winamac",
  },
  { offset: "-04:00", label: "Guyana Time", timezone: "America/Guyana" },
  {
    offset: "-04:00",
    label: "Paraguay Time",
    timezone: "America/Asuncion",
  },
  {
    offset: "-04:00",
    label: "Venezuela Time",
    timezone: "America/Caracas",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Buenos Aires",
    timezone: "America/Argentina/Buenos_Aires",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Catamarca",
    timezone: "America/Argentina/Catamarca",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Cordoba",
    timezone: "America/Argentina/Cordoba",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Jujuy",
    timezone: "America/Argentina/Jujuy",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - La Rioja",
    timezone: "America/Argentina/La_Rioja",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Mendoza",
    timezone: "America/Argentina/Mendoza",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Rio Gallegos",
    timezone: "America/Argentina/Rio_Gallegos",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Salta",
    timezone: "America/Argentina/Salta",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - San Juan",
    timezone: "America/Argentina/San_Juan",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - San Luis",
    timezone: "America/Argentina/San_Luis",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Tucuman",
    timezone: "America/Argentina/Tucuman",
  },
  {
    offset: "-03:00",
    label: "Argentina Standard Time - Ushuaia",
    timezone: "America/Argentina/Ushuaia",
  },
  {
    offset: "-03:00",
    label: "Atlantic Time - Bermuda",
    timezone: "Atlantic/Bermuda",
  },
  {
    offset: "-03:00",
    label: "Atlantic Time - Glace Bay",
    timezone: "America/Glace_Bay",
  },
  {
    offset: "-03:00",
    label: "Atlantic Time - Goose Bay",
    timezone: "America/Goose_Bay",
  },
  {
    offset: "-03:00",
    label: "Atlantic Time - Halifax",
    timezone: "America/Halifax",
  },
  {
    offset: "-03:00",
    label: "Atlantic Time - Moncton",
    timezone: "America/Moncton",
  },
  {
    offset: "-03:00",
    label: "Atlantic Time - Thule",
    timezone: "America/Thule",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Araguaina",
    timezone: "America/Araguaina",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Bahia",
    timezone: "America/Bahia",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Belem",
    timezone: "America/Belem",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Fortaleza",
    timezone: "America/Fortaleza",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Maceio",
    timezone: "America/Maceio",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Recife",
    timezone: "America/Recife",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Santarem",
    timezone: "America/Santarem",
  },
  {
    offset: "-03:00",
    label: "Brasilia Standard Time - Sao Paulo",
    timezone: "America/Sao_Paulo",
  },
  {
    offset: "-03:00",
    label: "Falkland Islands Standard Time",
    timezone: "Atlantic/Stanley",
  },
  {
    offset: "-03:00",
    label: "French Guiana Time",
    timezone: "America/Cayenne",
  },
  { offset: "-03:00", label: "Palmer Time", timezone: "Antarctica/Palmer" },
  {
    offset: "-03:00",
    label: "Punta Arenas Time",
    timezone: "America/Punta_Arenas",
  },
  {
    offset: "-03:00",
    label: "Rothera Time",
    timezone: "Antarctica/Rothera",
  },
  {
    offset: "-03:00",
    label: "Suriname Time",
    timezone: "America/Paramaribo",
  },
  {
    offset: "-03:00",
    label: "Uruguay Standard Time",
    timezone: "America/Montevideo",
  },
  {
    offset: "-02:30",
    label: "Newfoundland Time",
    timezone: "America/St_Johns",
  },
  {
    offset: "-02:00",
    label: "Fernando de Noronha Standard Time",
    timezone: "America/Noronha",
  },
  {
    offset: "-02:00",
    label: "South Georgia Time",
    timezone: "Atlantic/South_Georgia",
  },
  {
    offset: "-02:00",
    label: "St. Pierre & Miquelon Time",
    timezone: "America/Miquelon",
  },
  {
    offset: "-02:00",
    label: "West Greenland Time",
    timezone: "America/Nuuk",
  },
  {
    offset: "-01:00",
    label: "Cape Verde Standard Time",
    timezone: "Atlantic/Cape_Verde",
  },
  { offset: "+00:00", label: "Azores Time", timezone: "Atlantic/Azores" },
  {
    offset: "+00:00",
    label: "Coordinated Universal Time",
    timezone: "UTC",
  },
  {
    offset: "+00:00",
    label: "East Greenland Time",
    timezone: "America/Scoresbysund",
  },
  { offset: "+00:00", label: "Greenwich Mean Time", timezone: "Etc/GMT" },
  {
    offset: "+00:00",
    label: "Greenwich Mean Time - Abidjan",
    timezone: "Africa/Abidjan",
  },
  {
    offset: "+00:00",
    label: "Greenwich Mean Time - Bissau",
    timezone: "Africa/Bissau",
  },
  {
    offset: "+00:00",
    label: "Greenwich Mean Time - Danmarkshavn",
    timezone: "America/Danmarkshavn",
  },
  {
    offset: "+00:00",
    label: "Greenwich Mean Time - Monrovia",
    timezone: "Africa/Monrovia",
  },
  {
    offset: "+00:00",
    label: "Greenwich Mean Time - Reykjavik",
    timezone: "Atlantic/Reykjavik",
  },
  {
    offset: "+00:00",
    label: "Greenwich Mean Time - São Tomé",
    timezone: "Africa/Sao_Tome",
  },
  {
    offset: "+01:00",
    label: "Central European Standard Time - Algiers",
    timezone: "Africa/Algiers",
  },
  {
    offset: "+01:00",
    label: "Central European Standard Time - Tunis",
    timezone: "Africa/Tunis",
  },
  { offset: "+01:00", label: "Ireland Time", timezone: "Europe/Dublin" },
  {
    offset: "+01:00",
    label: "Morocco Time",
    timezone: "Africa/Casablanca",
  },
  {
    offset: "+01:00",
    label: "United Kingdom Time",
    timezone: "Europe/London",
  },
  {
    offset: "+01:00",
    label: "West Africa Standard Time - Lagos",
    timezone: "Africa/Lagos",
  },
  {
    offset: "+01:00",
    label: "West Africa Standard Time - Ndjamena",
    timezone: "Africa/Ndjamena",
  },
  {
    offset: "+01:00",
    label: "Western European Time - Canary",
    timezone: "Atlantic/Canary",
  },
  {
    offset: "+01:00",
    label: "Western European Time - Faroe",
    timezone: "Atlantic/Faroe",
  },
  {
    offset: "+01:00",
    label: "Western European Time - Lisbon",
    timezone: "Europe/Lisbon",
  },
  {
    offset: "+01:00",
    label: "Western European Time - Madeira",
    timezone: "Atlantic/Madeira",
  },
  {
    offset: "+01:00",
    label: "Western Sahara Time",
    timezone: "Africa/El_Aaiun",
  },
  {
    offset: "+02:00",
    label: "Central Africa Time - Juba",
    timezone: "Africa/Juba",
  },
  {
    offset: "+02:00",
    label: "Central Africa Time - Khartoum",
    timezone: "Africa/Khartoum",
  },
  {
    offset: "+02:00",
    label: "Central Africa Time - Maputo",
    timezone: "Africa/Maputo",
  },
  {
    offset: "+02:00",
    label: "Central Africa Time - Windhoek",
    timezone: "Africa/Windhoek",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Amsterdam",
    timezone: "Europe/Amsterdam",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Andorra",
    timezone: "Europe/Andorra",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Belgrade",
    timezone: "Europe/Belgrade",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Berlin",
    timezone: "Europe/Berlin",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Brussels",
    timezone: "Europe/Brussels",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Budapest",
    timezone: "Europe/Budapest",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Ceuta",
    timezone: "Africa/Ceuta",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Copenhagen",
    timezone: "Europe/Copenhagen",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Gibraltar",
    timezone: "Europe/Gibraltar",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Luxembourg",
    timezone: "Europe/Luxembourg",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Madrid",
    timezone: "Europe/Madrid",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Malta",
    timezone: "Europe/Malta",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Monaco",
    timezone: "Europe/Monaco",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Oslo",
    timezone: "Europe/Oslo",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Paris",
    timezone: "Europe/Paris",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Prague",
    timezone: "Europe/Prague",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Rome",
    timezone: "Europe/Rome",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Stockholm",
    timezone: "Europe/Stockholm",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Tirane",
    timezone: "Europe/Tirane",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Vienna",
    timezone: "Europe/Vienna",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Warsaw",
    timezone: "Europe/Warsaw",
  },
  {
    offset: "+02:00",
    label: "Central European Time - Zurich",
    timezone: "Europe/Zurich",
  },
  {
    offset: "+02:00",
    label: "Eastern European Standard Time - Kaliningrad",
    timezone: "Europe/Kaliningrad",
  },
  {
    offset: "+02:00",
    label: "Eastern European Standard Time - Tripoli",
    timezone: "Africa/Tripoli",
  },
  {
    offset: "+02:00",
    label: "South Africa Standard Time",
    timezone: "Africa/Johannesburg",
  },
  { offset: "+02:00", label: "Troll Time", timezone: "Antarctica/Troll" },
  {
    offset: "+03:00",
    label: "Arabian Standard Time - Baghdad",
    timezone: "Asia/Baghdad",
  },
  {
    offset: "+03:00",
    label: "Arabian Standard Time - Qatar",
    timezone: "Asia/Qatar",
  },
  {
    offset: "+03:00",
    label: "Arabian Standard Time - Riyadh",
    timezone: "Asia/Riyadh",
  },
  {
    offset: "+03:00",
    label: "East Africa Time",
    timezone: "Africa/Nairobi",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Athens",
    timezone: "Europe/Athens",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Beirut",
    timezone: "Asia/Beirut",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Bucharest",
    timezone: "Europe/Bucharest",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Cairo",
    timezone: "Africa/Cairo",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Chisinau",
    timezone: "Europe/Chisinau",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Gaza",
    timezone: "Asia/Gaza",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Hebron",
    timezone: "Asia/Hebron",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Helsinki",
    timezone: "Europe/Helsinki",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Kyiv",
    timezone: "Europe/Kiev",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Nicosia",
    timezone: "Asia/Nicosia",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Riga",
    timezone: "Europe/Riga",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Sofia",
    timezone: "Europe/Sofia",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Tallinn",
    timezone: "Europe/Tallinn",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Uzhhorod",
    timezone: "Europe/Uzhgorod",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Vilnius",
    timezone: "Europe/Vilnius",
  },
  {
    offset: "+03:00",
    label: "Eastern European Time - Zaporozhye",
    timezone: "Europe/Zaporozhye",
  },
  { offset: "+03:00", label: "Famagusta Time", timezone: "Asia/Famagusta" },
  { offset: "+03:00", label: "Israel Time", timezone: "Asia/Jerusalem" },
  { offset: "+03:00", label: "Jordan Time", timezone: "Asia/Amman" },
  { offset: "+03:00", label: "Kirov Time", timezone: "Europe/Kirov" },
  {
    offset: "+03:00",
    label: "Moscow Standard Time - Minsk",
    timezone: "Europe/Minsk",
  },
  {
    offset: "+03:00",
    label: "Moscow Standard Time - Moscow",
    timezone: "Europe/Moscow",
  },
  {
    offset: "+03:00",
    label: "Moscow Standard Time - Simferopol",
    timezone: "Europe/Simferopol",
  },
  { offset: "+03:00", label: "Syria Time", timezone: "Asia/Damascus" },
  { offset: "+03:00", label: "Türkiye Time", timezone: "Europe/Istanbul" },
  {
    offset: "+03:00",
    label: "Volgograd Standard Time",
    timezone: "Europe/Volgograd",
  },
  {
    offset: "+03:30",
    label: "Iran Standard Time",
    timezone: "Asia/Tehran",
  },
  {
    offset: "+04:00",
    label: "Armenia Standard Time",
    timezone: "Asia/Yerevan",
  },
  {
    offset: "+04:00",
    label: "Astrakhan Time",
    timezone: "Europe/Astrakhan",
  },
  {
    offset: "+04:00",
    label: "Azerbaijan Standard Time",
    timezone: "Asia/Baku",
  },
  {
    offset: "+04:00",
    label: "Georgia Standard Time",
    timezone: "Asia/Tbilisi",
  },
  { offset: "+04:00", label: "Gulf Standard Time", timezone: "Asia/Dubai" },
  {
    offset: "+04:00",
    label: "Mauritius Standard Time",
    timezone: "Indian/Mauritius",
  },
  { offset: "+04:00", label: "Réunion Time", timezone: "Indian/Reunion" },
  {
    offset: "+04:00",
    label: "Samara Standard Time",
    timezone: "Europe/Samara",
  },
  { offset: "+04:00", label: "Saratov Time", timezone: "Europe/Saratov" },
  { offset: "+04:00", label: "Seychelles Time", timezone: "Indian/Mahe" },
  {
    offset: "+04:00",
    label: "Ulyanovsk Time",
    timezone: "Europe/Ulyanovsk",
  },
  { offset: "+04:30", label: "Afghanistan Time", timezone: "Asia/Kabul" },
  {
    offset: "+05:00",
    label: "French Southern & Antarctic Time",
    timezone: "Indian/Kerguelen",
  },
  { offset: "+05:00", label: "Maldives Time", timezone: "Indian/Maldives" },
  { offset: "+05:00", label: "Mawson Time", timezone: "Antarctica/Mawson" },
  {
    offset: "+05:00",
    label: "Pakistan Standard Time",
    timezone: "Asia/Karachi",
  },
  { offset: "+05:00", label: "Tajikistan Time", timezone: "Asia/Dushanbe" },
  {
    offset: "+05:00",
    label: "Turkmenistan Standard Time",
    timezone: "Asia/Ashgabat",
  },
  {
    offset: "+05:00",
    label: "Uzbekistan Standard Time - Samarkand",
    timezone: "Asia/Samarkand",
  },
  {
    offset: "+05:00",
    label: "Uzbekistan Standard Time - Tashkent",
    timezone: "Asia/Tashkent",
  },
  {
    offset: "+05:00",
    label: "West Kazakhstan Time - Aqtau",
    timezone: "Asia/Aqtau",
  },
  {
    offset: "+05:00",
    label: "West Kazakhstan Time - Aqtobe",
    timezone: "Asia/Aqtobe",
  },
  {
    offset: "+05:00",
    label: "West Kazakhstan Time - Atyrau",
    timezone: "Asia/Atyrau",
  },
  {
    offset: "+05:00",
    label: "West Kazakhstan Time - Oral",
    timezone: "Asia/Oral",
  },
  {
    offset: "+05:00",
    label: "West Kazakhstan Time - Qyzylorda",
    timezone: "Asia/Qyzylorda",
  },
  {
    offset: "+05:00",
    label: "Yekaterinburg Standard Time",
    timezone: "Asia/Yekaterinburg",
  },
  {
    offset: "+05:30",
    label: "India Standard Time - Colombo",
    timezone: "Asia/Colombo",
  },
  {
    offset: "+05:30",
    label: "India Standard Time - Kolkata",
    timezone: "Asia/Kolkata",
  },
  { offset: "+05:45", label: "Nepal Time", timezone: "Asia/Kathmandu" },
  {
    offset: "+06:00",
    label: "Bangladesh Standard Time",
    timezone: "Asia/Dhaka",
  },
  { offset: "+06:00", label: "Bhutan Time", timezone: "Asia/Thimphu" },
  {
    offset: "+06:00",
    label: "East Kazakhstan Time - Almaty",
    timezone: "Asia/Almaty",
  },
  {
    offset: "+06:00",
    label: "East Kazakhstan Time - Kostanay",
    timezone: "Asia/Qostanay",
  },
  {
    offset: "+06:00",
    label: "Indian Ocean Time",
    timezone: "Indian/Chagos",
  },
  { offset: "+06:00", label: "Kyrgyzstan Time", timezone: "Asia/Bishkek" },
  { offset: "+06:00", label: "Omsk Standard Time", timezone: "Asia/Omsk" },
  { offset: "+06:00", label: "Urumqi Time", timezone: "Asia/Urumqi" },
  { offset: "+06:00", label: "Vostok Time", timezone: "Antarctica/Vostok" },
  {
    offset: "+06:30",
    label: "Cocos Islands Time",
    timezone: "Indian/Cocos",
  },
  { offset: "+06:30", label: "Myanmar Time", timezone: "Asia/Yangon" },
  { offset: "+07:00", label: "Barnaul Time", timezone: "Asia/Barnaul" },
  {
    offset: "+07:00",
    label: "Christmas Island Time",
    timezone: "Indian/Christmas",
  },
  { offset: "+07:00", label: "Davis Time", timezone: "Antarctica/Davis" },
  { offset: "+07:00", label: "Hovd Standard Time", timezone: "Asia/Hovd" },
  {
    offset: "+07:00",
    label: "Indochina Time - Bangkok",
    timezone: "Asia/Bangkok",
  },
  // {
  //   offset: "+07:00",
  //   label: "Indochina Time - Ho Chi Minh City",
  //   timezone: "Asia/Ho_Chi_Minh"
  // },
  {
    offset: "+07:00",
    label: "Krasnoyarsk Standard Time - Krasnoyarsk",
    timezone: "Asia/Krasnoyarsk",
  },
  {
    offset: "+07:00",
    label: "Krasnoyarsk Standard Time - Novokuznetsk",
    timezone: "Asia/Novokuznetsk",
  },
  {
    offset: "+07:00",
    label: "Novosibirsk Standard Time",
    timezone: "Asia/Novosibirsk",
  },
  { offset: "+07:00", label: "Tomsk Time", timezone: "Asia/Tomsk" },
  {
    offset: "+07:00",
    label: "Western Indonesia Time - Jakarta",
    timezone: "Asia/Jakarta",
  },
  {
    offset: "+07:00",
    label: "Western Indonesia Time - Pontianak",
    timezone: "Asia/Pontianak",
  },
  {
    offset: "+08:00",
    label: "Australian Western Standard Time",
    timezone: "Australia/Perth",
  },
  {
    offset: "+08:00",
    label: "Brunei Darussalam Time",
    timezone: "Asia/Brunei",
  },
  {
    offset: "+08:00",
    label: "Central Indonesia Time",
    timezone: "Asia/Makassar",
  },
  {
    offset: "+08:00",
    label: "China Standard Time - Macao",
    timezone: "Asia/Macau",
  },
  {
    offset: "+08:00",
    label: "China Standard Time - Shanghai",
    timezone: "Asia/Shanghai",
  },
  {
    offset: "+08:00",
    label: "Hong Kong Standard Time",
    timezone: "Asia/Hong_Kong",
  },
  {
    offset: "+08:00",
    label: "Irkutsk Standard Time",
    timezone: "Asia/Irkutsk",
  },
  {
    offset: "+08:00",
    label: "Malaysia Time - Kuala Lumpur",
    timezone: "Asia/Kuala_Lumpur",
  },
  {
    offset: "+08:00",
    label: "Malaysia Time - Kuching",
    timezone: "Asia/Kuching",
  },
  {
    offset: "+08:00",
    label: "Philippine Standard Time",
    timezone: "Asia/Manila",
  },
  {
    offset: "+08:00",
    label: "Singapore Standard Time",
    timezone: "Asia/Singapore",
  },
  {
    offset: "+08:00",
    label: "Taipei Standard Time",
    timezone: "Asia/Taipei",
  },
  {
    offset: "+08:00",
    label: "Ulaanbaatar Standard Time - Choibalsan",
    timezone: "Asia/Choibalsan",
  },
  {
    offset: "+08:00",
    label: "Ulaanbaatar Standard Time - Ulaanbaatar",
    timezone: "Asia/Ulaanbaatar",
  },
  {
    offset: "+08:45",
    label: "Australian Central Western Standard Time",
    timezone: "Australia/Eucla",
  },
  { offset: "+09:00", label: "East Timor Time", timezone: "Asia/Dili" },
  {
    offset: "+09:00",
    label: "Eastern Indonesia Time",
    timezone: "Asia/Jayapura",
  },
  {
    offset: "+09:00",
    label: "Japan Standard Time",
    timezone: "Asia/Tokyo",
  },
  {
    offset: "+09:00",
    label: "Korean Standard Time - Pyongyang",
    timezone: "Asia/Pyongyang",
  },
  {
    offset: "+09:00",
    label: "Korean Standard Time - Seoul",
    timezone: "Asia/Seoul",
  },
  { offset: "+09:00", label: "Palau Time", timezone: "Pacific/Palau" },
  {
    offset: "+09:00",
    label: "Yakutsk Standard Time - Chita",
    timezone: "Asia/Chita",
  },
  {
    offset: "+09:00",
    label: "Yakutsk Standard Time - Khandyga",
    timezone: "Asia/Khandyga",
  },
  {
    offset: "+09:00",
    label: "Yakutsk Standard Time - Yakutsk",
    timezone: "Asia/Yakutsk",
  },
  {
    offset: "+09:30",
    label: "Australian Central Standard Time",
    timezone: "Australia/Darwin",
  },
  {
    offset: "+09:30",
    label: "Central Australia Time - Adelaide",
    timezone: "Australia/Adelaide",
  },
  {
    offset: "+09:30",
    label: "Central Australia Time - Broken Hill",
    timezone: "Australia/Broken_Hill",
  },
  {
    offset: "+10:00",
    label: "Australian Eastern Standard Time - Brisbane",
    timezone: "Australia/Brisbane",
  },
  {
    offset: "+10:00",
    label: "Australian Eastern Standard Time - Lindeman",
    timezone: "Australia/Lindeman",
  },
  {
    offset: "+10:00",
    label: "Chamorro Standard Time",
    timezone: "Pacific/Guam",
  },
  { offset: "+10:00", label: "Chuuk Time", timezone: "Pacific/Chuuk" },
  {
    offset: "+10:00",
    label: "Eastern Australia Time - Hobart",
    timezone: "Australia/Hobart",
  },
  {
    offset: "+10:00",
    label: "Eastern Australia Time - Macquarie",
    timezone: "Antarctica/Macquarie",
  },
  {
    offset: "+10:00",
    label: "Eastern Australia Time - Melbourne",
    timezone: "Australia/Melbourne",
  },
  {
    offset: "+10:00",
    label: "Eastern Australia Time - Sydney",
    timezone: "Australia/Sydney",
  },
  {
    offset: "+10:00",
    label: "Papua New Guinea Time",
    timezone: "Pacific/Port_Moresby",
  },
  {
    offset: "+10:00",
    label: "Vladivostok Standard Time - Ust-Nera",
    timezone: "Asia/Ust-Nera",
  },
  {
    offset: "+10:00",
    label: "Vladivostok Standard Time - Vladivostok",
    timezone: "Asia/Vladivostok",
  },
  {
    offset: "+10:30",
    label: "Lord Howe Time",
    timezone: "Australia/Lord_Howe",
  },
  {
    offset: "+11:00",
    label: "Bougainville Time",
    timezone: "Pacific/Bougainville",
  },
  { offset: "+11:00", label: "Casey Time", timezone: "Antarctica/Casey" },
  { offset: "+11:00", label: "Kosrae Time", timezone: "Pacific/Kosrae" },
  {
    offset: "+11:00",
    label: "Magadan Standard Time",
    timezone: "Asia/Magadan",
  },
  {
    offset: "+11:00",
    label: "New Caledonia Standard Time",
    timezone: "Pacific/Noumea",
  },
  {
    offset: "+11:00",
    label: "Norfolk Island Time",
    timezone: "Pacific/Norfolk",
  },
  { offset: "+11:00", label: "Ponape Time", timezone: "Pacific/Pohnpei" },
  {
    offset: "+11:00",
    label: "Sakhalin Standard Time",
    timezone: "Asia/Sakhalin",
  },
  {
    offset: "+11:00",
    label: "Solomon Islands Time",
    timezone: "Pacific/Guadalcanal",
  },
  {
    offset: "+11:00",
    label: "Srednekolymsk Time",
    timezone: "Asia/Srednekolymsk",
  },
  {
    offset: "+11:00",
    label: "Vanuatu Standard Time",
    timezone: "Pacific/Efate",
  },
  {
    offset: "+12:00",
    label: "Anadyr Standard Time",
    timezone: "Asia/Anadyr",
  },
  {
    offset: "+12:00",
    label: "Fiji Standard Time",
    timezone: "Pacific/Fiji",
  },
  {
    offset: "+12:00",
    label: "Gilbert Islands Time",
    timezone: "Pacific/Tarawa",
  },
  {
    offset: "+12:00",
    label: "Marshall Islands Time - Kwajalein",
    timezone: "Pacific/Kwajalein",
  },
  {
    offset: "+12:00",
    label: "Marshall Islands Time - Majuro",
    timezone: "Pacific/Majuro",
  },
  { offset: "+12:00", label: "Nauru Time", timezone: "Pacific/Nauru" },
  {
    offset: "+12:00",
    label: "New Zealand Time",
    timezone: "Pacific/Auckland",
  },
  {
    offset: "+12:00",
    label: "Petropavlovsk-Kamchatski Standard Time",
    timezone: "Asia/Kamchatka",
  },
  { offset: "+12:00", label: "Tuvalu Time", timezone: "Pacific/Funafuti" },
  { offset: "+12:00", label: "Wake Island Time", timezone: "Pacific/Wake" },
  {
    offset: "+12:00",
    label: "Wallis & Futuna Time",
    timezone: "Pacific/Wallis",
  },
  { offset: "+12:45", label: "Chatham Time", timezone: "Pacific/Chatham" },
  {
    offset: "+13:00",
    label: "Apia Standard Time",
    timezone: "Pacific/Apia",
  },
  {
    offset: "+13:00",
    label: "Phoenix Islands Time",
    timezone: "Pacific/Kanton",
  },
  { offset: "+13:00", label: "Tokelau Time", timezone: "Pacific/Fakaofo" },
  {
    offset: "+13:00",
    label: "Tonga Standard Time",
    timezone: "Pacific/Tongatapu",
  },
  {
    offset: "+14:00",
    label: "Line Islands Time",
    timezone: "Pacific/Kiritimati",
  },
];
